"""Deterministic rendered content for managed files and reports."""

from __future__ import annotations

import json
from typing import Any, Dict

from .constants import (
    DEFAULT_ALPHA_CODEX_VERSION,
    DEFAULT_STABLE_CODEX_VERSION,
    GITIGNORE_BEGIN,
    GITIGNORE_END,
    README_MARKER,
    SCHEMA_VERSION,
    SCRIPT_NAME,
    SCRIPT_VERSION,
    SCRIPT_MARKER,
)
from .models import Config, Layout
from .runtime import utc_now_iso


def build_local_package_json(codex_version: str) -> str:
    """Return the deterministic package.json content for `.codex-local/`."""

    payload = {
        "name": "codex-local-managed-install",
        "private": True,
        "devDependencies": {
            "@openai/codex": codex_version,
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build_metadata(config: Config) -> Dict[str, Any]:
    """Build the metadata document recorded under the managed local directory."""

    return {
        "schema_version": SCHEMA_VERSION,
        "script_name": SCRIPT_NAME,
        "script_version": SCRIPT_VERSION,
        "generated_at": utc_now_iso(),
        "project_root": str(config.project_root),
        "codex_version": config.codex_version,
        "shared_home": config.shared_home,
        "version_source": config.version_source,
        "paths": {
            "local_dir": config.layout.local_dir_relative,
            "codex_home_dir": config.layout.codex_home_relative,
            "launcher": config.layout.launcher_relative,
            "readme_local": config.layout.readme_relative,
        },
    }


def build_gitignore_block(layout: Layout) -> str:
    """Return the managed `.gitignore` block."""

    lines = [
        GITIGNORE_BEGIN,
        "{}/".format(layout.local_dir_relative.rstrip("/")),
        "{}/".format(layout.codex_home_relative.rstrip("/")),
        layout.readme_relative,
        GITIGNORE_END,
        "",
    ]
    return "\n".join(lines)


def build_launcher_content(config: Config) -> str:
    """Build the generated shell launcher."""

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# {}".format(SCRIPT_MARKER),
        "# Generated by {}".format(SCRIPT_NAME),
        "#",
        "# This launcher keeps the Codex npm package local to the repository by",
        "# invoking npx with --prefix against the managed local directory.",
        "#",
        "# In default mode it also redirects HOME into the managed project Codex",
        "# home directory so auth, sessions, logs, and other Codex state remain",
        "# isolated per project.",
        "",
        'repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
        'local_prefix="$repo_root/{}"'.format(config.layout.local_dir_relative),
        'export NPM_CONFIG_CACHE="$local_prefix/.npm-cache"',
        'export CODEX_LOCAL_MANAGED_BY="{}"'.format(SCRIPT_NAME),
    ]

    if config.shared_home:
        lines.extend(
            [
                "# Shared-home mode leaves HOME unchanged so the operator's",
                "# normal ~/.codex state is reused across projects.",
            ]
        )
    else:
        lines.extend(
            [
                'export HOME="$repo_root/{}"'.format(config.layout.codex_home_relative),
                'export XDG_CONFIG_HOME="$HOME/.config"',
                'export XDG_CACHE_HOME="$HOME/.cache"',
                'export XDG_STATE_HOME="$HOME/.local/state"',
                'export XDG_DATA_HOME="$HOME/.local/share"',
            ]
        )

    lines.extend(
        [
            'exec npx --prefix "$local_prefix" codex "$@"',
            "",
        ]
    )
    return "\n".join(lines)


def build_local_readme_content(config: Config) -> str:
    """Build the generated project-local operator README."""

    lines = [
        README_MARKER,
        "# Local Codex Start Guide",
        "",
        "This file was generated by `{}` and is intended for local operator use.".format(
            SCRIPT_NAME
        ),
        "It is ignored on purpose and should not be committed.",
        "",
        "## Managed Paths",
        "",
        "- Local install: `{}`".format(config.layout.local_dir_relative),
        "- Local Codex home: `{}`".format(config.layout.codex_home_relative),
        "- Launcher: `{}`".format(config.layout.launcher_relative),
        "- This README: `{}`".format(config.layout.readme_relative),
        "",
        "## Installed Version",
        "",
        "- Requested Codex version: `{}`".format(config.codex_version),
        "- Version source: `{}`".format(config.version_source),
        "- HOME mode: `{}`".format(
            "shared user HOME" if config.shared_home else "project-local isolated HOME"
        ),
        "",
        "## Start Codex",
        "",
        "```bash",
        "./{}".format(config.layout.launcher_relative),
        "```",
        "",
        "## Resume Codex",
        "",
        "```bash",
        "./{} resume".format(config.layout.launcher_relative),
        "./{} resume --last".format(config.layout.launcher_relative),
        "```",
        "",
        "## Audit",
        "",
        "```bash",
        "npm audit --prefix ./{}".format(config.layout.local_dir_relative),
        "```",
        "",
        "## Inspect Managed State",
        "",
        "```bash",
        "{} --inspect .".format(SCRIPT_NAME),
        "```",
        "",
        "## Self-Test Managed State",
        "",
        "```bash",
        "{} --selftest .".format(SCRIPT_NAME),
        "```",
        "",
        "## Upgrade Within Current Channel",
        "",
        "```bash",
        "{} --upgrade .".format(SCRIPT_NAME),
        "```",
        "",
        "## Upgrade To Latest Alpha",
        "",
        "```bash",
        "{} --upgrade-to-alpha .".format(SCRIPT_NAME),
        "```",
        "",
        "## Downgrade To Latest Stable",
        "",
        "```bash",
        "{} --downgrade-to-stable .".format(SCRIPT_NAME),
        "```",
        "",
        "## Uninstall Managed Setup",
        "",
        "```bash",
        "{} --uninstall .".format(SCRIPT_NAME),
        "```",
        "",
    ]
    return "\n".join(lines)


def local_package_json_looks_managed(content: str) -> bool:
    """Return True when package.json content matches the managed shape."""

    try:
        payload = json.loads(content)
    except json.JSONDecodeError:
        return False

    if not isinstance(payload, dict):
        return False
    if payload.get("name") != "codex-local-managed-install":
        return False
    if payload.get("private") is not True:
        return False

    dev_dependencies = payload.get("devDependencies")
    if not isinstance(dev_dependencies, dict):
        return False
    version = dev_dependencies.get("@openai/codex")
    return isinstance(version, str) and bool(version)


def build_install_summary(config: Config) -> str:
    """Return the operator summary shown after install and upgrade operations."""

    lines = [
        "Operation complete.",
        "",
        "Project root: {}".format(config.project_root),
        "Operation: {}".format(config.operation),
        "Pinned Codex version: {}".format(config.codex_version),
        "Version source: {}".format(config.version_source),
        "Local package manifest: {}".format(config.layout.local_package_json_path),
        "Metadata file: {}".format(config.layout.metadata_path),
        "Launcher: {}".format(config.layout.launcher_path),
        "Local README: {}".format(config.layout.readme_path),
        "HOME mode: {}".format(
            "shared user HOME" if config.shared_home else "project-local isolated HOME"
        ),
        "",
        "Recommended usage:",
        "  {}".format(config.layout.launcher_path),
        "  {} resume".format(config.layout.launcher_path),
        "  {} resume --last".format(config.layout.launcher_path),
        "",
        "Audit command:",
        "  npm audit --prefix {}".format(config.layout.local_dir),
    ]
    return "\n".join(lines)


def build_known_versions() -> Dict[str, str]:
    """Return the known stable and alpha Codex versions."""

    return {
        "latest_known_stable": DEFAULT_STABLE_CODEX_VERSION,
        "latest_known_alpha": DEFAULT_ALPHA_CODEX_VERSION,
    }
